spring:
  profiles:
    active: local
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false
  cloud:
    discovery:
      enabled: true
  mail:
    host: smtp.yandex.ru
    port: 465
    username: pulsecore@yandex.ru
    password: alhxsixgscelcnfp
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      type: BATCH
    consumer:
      max-poll-records: 500
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.pulsecore.shared.dto.event

server:
  port: 8083
  forward-headers-strategy: framework

logging:
  level:
    root: WARN
    ru.pulsecore: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    org.springframework.cloud: WARN
    org.hibernate: WARN
app:
  vapid:
    public-key: BA_SIwQSoBdxuH6J0AbK3nKQt74JOmP5H4QlHc71WhqnhfsJfPJoNZLXDCsx8lVDJfqU7bxxEZ0dFiwt64pgQo0
    private-key: _D_M98-kAUX-iQQcjOhv1DUiJPhRL13HNpw7xW4N8EE

  mail:
    from: pulsecore@yandex.ru
  admin:
    email: evgenypavlov666@yandex.ru

eureka:
  instance:
    preferIpAddress: true