spring:
  profiles:
    active: local
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8084
  forward-headers-strategy: framework

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com:netflix:discovery: WARN


app:
  admin:
    email: evgenypavlov666@yandex.ru