spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.pulsecore.shared.dto.event,ru.pulsecore.shared.context,ru.pulsecore.shared.dto

  cloud:
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: 7e0bafe1a35f4328866b5071b0e9283d
            client-secret: 9eb033780bba40ee9f7e24df5a67f454
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
            scope:
              - login:email
              - login:info
              - login:default_phone
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id

  datasource:
    url: jdbc:postgresql://localhost:5432/botdb
    username: botuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  data:
    redis:
      host: localhost
      port: 6379
      password: redispass

jwt:
  private-key: classpath:private.pem
  public-key: classpath:public.pem
  public-key-location: classpath:public.pem
  access-token-ttl: 60m
  refresh-token-ttl: 30d
  issuer: pulsecore-user-service



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8080

logging:
  level:
    ru.pulsecore: INFO
    ru.pulsecore.user_service.config.RequestLoggingFilter: WARN
    ru.pulsecore.user_service.client: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN



# Включаем Circuit Breaker для Feign


eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  security:
    public-urls:
      - /
      - /index.html
      - /register.html
      - /api/players
      - /subscribe.html
      - /profile.html
      - /dashboard.html
      - /img.png
      - /favicon.ico
      - /robots.txt
      - /error
      - /api/auth/**
      - /api/payment/webhook
      - /oauth-finish.html
      - /manifest.json
      - /api/internal/**
    authenticated-urls:
      - /api/player/**
    admin-urls:
      - /admin.html
      - /api/admin/**
    oauth:
      unknown-email-domain: "@unknown.pulsecore"


  base-url: http://localhost:8080
  qr-color: "#14b8a6"
  admin:
    email: evgenypavlov666@yandex.ru

