spring:
  profiles:
    active: local
  application:
    name: admin-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enabled: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8085
  forward-headers-strategy: framework